<a href="https://colab.research.google.com/github/thirumaleshyadav220-netizen/numpy/blob/main/t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#create numpy arrays with single dim
import numpy as np
a=44
value=np.array(a)
print(value)
print(type(value))


44
<class 'numpy.ndarray'>


In [2]:
#array with group of vales
import numpy as np
detail=((10,20,30,40,50),(60,70,80,90,100))
sales=np.array(detail)
print(sales)
print(type(sales))
print(sales.ndim)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>
2


In [3]:
#acessing elements from arrays using indexing and slising
import numpy as np
details=[10,20,30,40,50,60,70,80,90,100]
sales=np.array(details)
print(sales)
print(type(sales))
print(sales[0])
print(sales[1])
print(sales[2])
print(sales[3])
print(sales[4])
print(sales[5])
print(sales[6::2])
print(sales[:])
print(sales[::-1])


[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>
10
20
30
40
50
60
[70 90]
[ 10  20  30  40  50  60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10]
