<a href="https://colab.research.google.com/github/thirumaleshyadav220-netizen/numpy/blob/main/t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>
10
20
30
40
50
60
[70 90]
[ 10  20  30  40  50  60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10]


In [ ]:
#create numpy arrays with single dim
import numpy as np
a=44
value=np.array(a)
print(value)
print(type(value))


In [2]:
#array with group of vales
import numpy as np
detail=((10,20,30,40,50),(60,70,80,90,100))
sales=np.array(detail)
print(sales)
print(type(sales))
print(sales.ndim)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>
2
